/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mibs.init.cabinet;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.lang.reflect.Method;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import java.util.Optional;
import java.util.Properties;
import java.util.TreeMap;
import java.util.concurrent.TimeoutException;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;

import org.apache.commons.lang3.SerializationUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;
import com.rabbitmq.client.DeliverCallback;

public class СabinetAgent extends Actions{
	
	private static final int PORT=5672;
	private static final Logger logger = LogManager.getLogger(СabinetAgent.class.getName());

	public String getGreeting() {
		return "Hello world.";
	}
	public СabinetAgent(String conf) {
		super( conf );
	}
	
	private Optional<Channel> connectToRabbit(String host, String login, String password) {
		ConnectionFactory factory = new ConnectionFactory();
		factory.setHost( host );
		factory.setUsername( login );
		factory.setPassword( password );
		factory.setPort(PORT);
	
		Connection connection;
		Channel channel = null;
		try {
			connection = factory.newConnection();
			channel = connection.createChannel();
		
		} catch (IOException e) {
			logger.error("Error! IO Exception with message: " + e.getMessage());
			exit();
		} catch (TimeoutException e) {
			logger.error("Error! Timeout Exception with message: " + e.getMessage());
			exit();
		}

		return channel != null ? Optional.of(channel) : Optional.empty();

	}
	
	private void run() {
		Optional<Channel> optionalLocalChannel = connectToRabbit( rabbitmqHost, rabbitmqLogin, rabbitmqPassword );
		if (!optionalLocalChannel.isPresent()) {
			logger.error("Error! Fail to make connection to local rabbitmq.");
			exit() ;
		}
		channel = optionalLocalChannel.get();
		
		try {
			channel.queueDeclare(localInQueue, true, false, false, null);
			channel.queueDeclare(localOutQueue, true, false, false, null);
			channel.queueDeclare(inboundQueue, true, false, false, null);
			
			channel.exchangeDeclare(directExchange, "direct", true, false, null);
			
			DeliverCallback deliveryCallback = (consumerTag, delivery) -> {
				
				RabbitmqCommandMessage<?> msg = (RabbitmqCommandMessage<?>) SerializationUtils.deserialize(delivery.getBody());
				
				System.out.println( msg.getCommand() );
				
				commands.get( msg.getCommand() ).accept( msg );
			};
			channel.basicConsume(localInQueue, true, deliveryCallback, consumerTag -> { });
			channel.basicConsume(inboundQueue, true, deliveryCallback, consumerTag -> { });
			
		} catch (IOException e) {
			logger.error("Error! IO Exception while declearing queue:  " + inboundQueue + " with message: " + e.getMessage());
			exit();
		}
		

	}

	public static void main(String[] args) {

		if (args.length > 0 && args[0].endsWith(".properties")) {
			СabinetAgent app = new СabinetAgent( args[0] );
			System.out.println(app.getGreeting());
			app.run();

		} else {
			System.out.println("Usage: java -jar /path/to/mibs-cabinet-agent-all.jar /path/to/application.properties");
			exit();
		}

	}
	
}
